version: 0.2

phases:
  install:
    commands:
      echo "Checking out master branch";
      git fetch;
      git checkout master;
      echo "Installing MXNet";
      apt-get update;
      pip install --upgrade pip;
      pip install mxnet --pre;
      echo "Installing Tensorflow";
      pip install tensorflow==1.15.0;
      echo "Installing Theano";
      pip install theano;
      pip install pillow;
      sudo apt-get -y install graphviz;
      pip install graphviz;
      pip install pydot;
      pip install nose;
      pip install PyYAML==3.13;
      pip install pytest==3.6.3;
      pip install pytest-xdist==1.22.2;
      echo "Installing Keras from source";
      pip install -e .[visualize,tests];

  build:
    commands:
      echo "Running PEP tests";
      py.test --pep8 -m pep8 -n0;
      echo "Running Keras Unit Tests and Integration Tests for all the backends";
      python -m pytest tests/;