version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      echo $CODEBUILD_SOURCE_VERSION;
      PRID=$(echo $CODEBUILD_SOURCE_VERSION | sed "s/pr/pull/g");
      echo "Checking out $PRID";
      git fetch origin $PRID/head:pr_test;
      git checkout pr_test;
      echo "Installing MXNet";
      apt-get update;
      sudo apt-get install python3.7-dev;
      python3.7 -m pip install pip;
      python3.7 -m pip install mxnet --pre;
      echo "Installing Tensorflow";
      python3.7 -m pip install tensorflow==1.15.0;
      echo "Installing Theano";
      python3.7 -m pip install theano;
      python3.7 -m pip install pillow;
      sudo apt-get -y install graphviz;
      python3.7 -m pip install graphviz;
      python3.7 -m pip install pydot;
      python3.7 -m pip install nose;
      python3.7 -m pip install --ignore-installed PyYAML==3.13;
      python3.7 -m pip install pytest==3.6.3;
      python3.7 -m pip install pytest-xdist==1.22.2;
      echo "Installing Keras from source";
      python3.7 -m pip install -e .[visualize,tests];

  build:
    commands:
      echo "Running PEP tests";
      py.test --pep8 -m pep8 -n0;
      echo "Running Keras Unit Tests and Integration Tests for all the backends";
      python3.7 -m pytest tests/;